config/routes.rb
ProjectCis4339::Application.routes.draw do
  resources :physician_availabilities

  resources :appointments

  resources :diagnostic_codes

  resources :weekday_availabilities

  resources :physicians

  resources :patients

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base

  belongs_to :appointment

end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnostic_codes }
    end
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
    @diagnostic_code = DiagnosticCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnostic_code }
    end
  end

  # GET /diagnostic_codes/new
  # GET /diagnostic_codes/new.json
  def new
    @diagnostic_code = DiagnosticCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnostic_code }
    end
  end

  # GET /diagnostic_codes/1/edit
  def edit
    @diagnostic_code = DiagnosticCode.find(params[:id])
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(params[:diagnostic_code])

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render json: @diagnostic_code, status: :created, location: @diagnostic_code }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnostic_codes/1
  # PUT /diagnostic_codes/1.json
  def update
    @diagnostic_code = DiagnosticCode.find(params[:id])

    respond_to do |format|
      if @diagnostic_code.update_attributes(params[:diagnostic_code])
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code = DiagnosticCode.find(params[:id])
    @diagnostic_code.destroy

    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for(@diagnostic_code) do |f| %>
  <% if @diagnostic_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h2>

      <ul>
      <% @diagnostic_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Code_Number' %><br />
    <%= f.number_field :code_number %>
  </div>
  <div class="field">
    <%= f.label 'Code_Name' %><br />
    <%= f.text_field :code_name %>
  </div>
  <div class="field">
    <%= f.label 'Cost' %><br />
    <%= f.number_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnostic_codes/edit.html.erb
<h1>Editing diagnostic_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic_code %> |
<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/index.html.erb
<h1>Listing diagnostic_codes</h1>

<table>
  <tr>
    <th>Code number</th>
    <th>Code name</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagnostic_codes.each do |diagnostic_code| %>
  <tr>
    <td><%= diagnostic_code.code_number %></td>
    <td><%= diagnostic_code.code_name %></td>
    <td><%= diagnostic_code.cost %></td>
    <td><%= link_to 'Show', diagnostic_code %></td>
    <td><%= link_to 'Edit', edit_diagnostic_code_path(diagnostic_code) %></td>
    <td><%= link_to 'Destroy', diagnostic_code, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagnostic code', new_diagnostic_code_path %>

app/views/diagnostic_codes/new.html.erb
<h1>New diagnostic_code</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code number:</b>
  <%= @diagnostic_code.code_number %>
</p>

<p>
  <b>Code name:</b>
  <%= @diagnostic_code.code_name %>
</p>

<p>
  <b>Cost:</b>
  <%= @diagnostic_code.cost %>
</p>


<%= link_to 'Edit', edit_diagnostic_code_path(@diagnostic_code) %> |
<%= link_to 'Back', diagnostic_codes_path %>