config/routes.rb
ProjectCis4339::Application.routes.draw do
  resources :physician_availabilities

  resources :appointments

  resources :diagnostic_codes

  resources :weekday_availabilities

  resources :physicians

  resources :patients

end

app/models/physician.rb
class Physician < ActiveRecord::Base

  belongs_to :physician_availability
  has_many :appointments
  has_many :patients, through: :appointments

end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @physicians }
    end
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
    @physician = Physician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @physician }
    end
  end

  # GET /physicians/new
  # GET /physicians/new.json
  def new
    @physician = Physician.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @physician }
    end
  end

  # GET /physicians/1/edit
  def edit
    @physician = Physician.find(params[:id])
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(params[:physician])

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render json: @physician, status: :created, location: @physician }
      else
        format.html { render action: "new" }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /physicians/1
  # PUT /physicians/1.json
  def update
    @physician = Physician.find(params[:id])

    respond_to do |format|
      if @physician.update_attributes(params[:physician])
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Last Name' %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label 'Physician Availability' %><br />
    <%= f.collection_select :physician_availability_id, PhysicianAvailability.all, :id, :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing physicians</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>Physician availability</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @physicians.each do |physician| %>
  <tr>
    <td><%= physician.last_name %></td>
    <td><%= physician.physician_availability.status %></td>
    <td><%= link_to 'Show', physician %></td>
    <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
    <td><%= link_to 'Destroy', physician, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @physician.last_name %>
</p>

<p>
  <b>Physician availability:</b>
  <%= @physician.physician_availability_id %>
</p>


<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>