config/routes.rb
ProjectCis4339::Application.routes.draw do
  resources :physician_availabilities

  resources :appointments

  resources :diagnostic_codes

  resources :weekday_availabilities

  resources :physicians

  resources :patients

end

app/models/physician_availability.rb
class PhysicianAvailability < ActiveRecord::Base

  has_many :physicians

end

app/controllers/physician_availabilities_controller.rb
class PhysicianAvailabilitiesController < ApplicationController
  # GET /physician_availabilities
  # GET /physician_availabilities.json
  def index
    @physician_availabilities = PhysicianAvailability.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @physician_availabilities }
    end
  end

  # GET /physician_availabilities/1
  # GET /physician_availabilities/1.json
  def show
    @physician_availability = PhysicianAvailability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @physician_availability }
    end
  end

  # GET /physician_availabilities/new
  # GET /physician_availabilities/new.json
  def new
    @physician_availability = PhysicianAvailability.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @physician_availability }
    end
  end

  # GET /physician_availabilities/1/edit
  def edit
    @physician_availability = PhysicianAvailability.find(params[:id])
  end

  # POST /physician_availabilities
  # POST /physician_availabilities.json
  def create
    @physician_availability = PhysicianAvailability.new(params[:physician_availability])

    respond_to do |format|
      if @physician_availability.save
        format.html { redirect_to @physician_availability, notice: 'Physician availability was successfully created.' }
        format.json { render json: @physician_availability, status: :created, location: @physician_availability }
      else
        format.html { render action: "new" }
        format.json { render json: @physician_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /physician_availabilities/1
  # PUT /physician_availabilities/1.json
  def update
    @physician_availability = PhysicianAvailability.find(params[:id])

    respond_to do |format|
      if @physician_availability.update_attributes(params[:physician_availability])
        format.html { redirect_to @physician_availability, notice: 'Physician availability was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @physician_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physician_availabilities/1
  # DELETE /physician_availabilities/1.json
  def destroy
    @physician_availability = PhysicianAvailability.find(params[:id])
    @physician_availability.destroy

    respond_to do |format|
      format.html { redirect_to physician_availabilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/physician_availabilities_helper.rb
module PhysicianAvailabilitiesHelper
end

app/views/physician_availabilities/_form.html.erb
<%= form_for(@physician_availability) do |f| %>
  <% if @physician_availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician_availability.errors.count, "error") %> prohibited this physician_availability from being saved:</h2>

      <ul>
      <% @physician_availability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physician_availabilities/edit.html.erb
<h1>Editing physician_availability</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician_availability %> |
<%= link_to 'Back', physician_availabilities_path %>

app/views/physician_availabilities/index.html.erb
<h1>Listing physician_availabilities</h1>

<table>
  <tr>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @physician_availabilities.each do |physician_availability| %>
  <tr>
    <td><%= physician_availability.status %></td>
    <td><%= link_to 'Show', physician_availability %></td>
    <td><%= link_to 'Edit', edit_physician_availability_path(physician_availability) %></td>
    <td><%= link_to 'Destroy', physician_availability, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physician availability', new_physician_availability_path %>

app/views/physician_availabilities/new.html.erb
<h1>New physician_availability</h1>

<%= render 'form' %>

<%= link_to 'Back', physician_availabilities_path %>

app/views/physician_availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @physician_availability.status %>
</p>


<%= link_to 'Edit', edit_physician_availability_path(@physician_availability) %> |
<%= link_to 'Back', physician_availabilities_path %>