config/routes.rb
ProjectCis4339::Application.routes.draw do
  resources :physician_availabilities

  resources :appointments

  resources :diagnostic_codes

  resources :weekday_availabilities

  resources :physicians

  resources :patients

end

app/models/weekday_availability.rb
class WeekdayAvailability < ActiveRecord::Base

  belongs_to :appointment

end

app/controllers/weekday_availabilities_controller.rb
class WeekdayAvailabilitiesController < ApplicationController


  # GET /weekday_availabilities
  # GET /weekday_availabilities.json
  def index
    @weekday_availabilities = WeekdayAvailability.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weekday_availabilities }
    end
  end

  # GET /weekday_availabilities/1
  # GET /weekday_availabilities/1.json
  def show
    @weekday_availability = WeekdayAvailability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weekday_availability }
    end
  end

  # GET /weekday_availabilities/new
  # GET /weekday_availabilities/new.json
  def new
    @weekday_availability = WeekdayAvailability.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weekday_availability }
    end
  end

  # GET /weekday_availabilities/1/edit
  def edit
    @weekday_availability = WeekdayAvailability.find(params[:id])
  end

  # POST /weekday_availabilities
  # POST /weekday_availabilities.json
  def create
    @weekday_availability = WeekdayAvailability.new(params[:weekday_availability])

    respond_to do |format|
      if @weekday_availability.save
        format.html { redirect_to @weekday_availability, notice: 'Weekday availability was successfully created.' }
        format.json { render json: @weekday_availability, status: :created, location: @weekday_availability }
      else
        format.html { render action: "new" }
        format.json { render json: @weekday_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weekday_availabilities/1
  # PUT /weekday_availabilities/1.json
  def update
    @weekday_availability = WeekdayAvailability.find(params[:id])

    respond_to do |format|
      if @weekday_availability.update_attributes(params[:weekday_availability])
        format.html { redirect_to @weekday_availability, notice: 'Weekday availability was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weekday_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekday_availabilities/1
  # DELETE /weekday_availabilities/1.json
  def destroy
    @weekday_availability = WeekdayAvailability.find(params[:id])
    @weekday_availability.destroy

    respond_to do |format|
      format.html { redirect_to weekday_availabilities_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_weekday_availability
    @weekday_availability = WeekdayAvailability.find(params[:id])
  end

  def slot_params
    params.require(:slot).permit(:time_block)
  end
end

app/helpers/weekday_availabilities_helper.rb
module WeekdayAvailabilitiesHelper
end

app/views/weekday_availabilities/_form.html.erb
<%= form_for(@weekday_availability) do |f| %>
  <% if @weekday_availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weekday_availability.errors.count, "error") %> prohibited this weekday_availability from being saved:</h2>

      <ul>
      <% @weekday_availability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Weekday' %><br />
    <%= f.text_field :w_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weekday_availabilities/edit.html.erb
<h1>Editing weekday_availability</h1>

<%= render 'form' %>

<%= link_to 'Show', @weekday_availability %> |
<%= link_to 'Back', weekday_availabilities_path %>

app/views/weekday_availabilities/index.html.erb
<h1>Listing weekday_availabilities</h1>

<table>
  <tr>
    <th>Week day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weekday_availabilities.each do |weekday_availability| %>
  <tr>
    <td><%= weekday_availability.w_day %></td>
    <td><%= link_to 'Show', weekday_availability %></td>
    <td><%= link_to 'Edit', edit_weekday_availability_path(weekday_availability) %></td>
    <td><%= link_to 'Destroy', weekday_availability, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weekday availability', new_weekday_availability_path %>

app/views/weekday_availabilities/new.html.erb
<h1>New weekday_availability</h1>

<%= render 'form' %>

<%= link_to 'Back', weekday_availabilities_path %>

app/views/weekday_availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>W day:</b>
  <%= @weekday_availability.w_day %>
</p>


<%= link_to 'Edit', edit_weekday_availability_path(@weekday_availability) %> |
<%= link_to 'Back', weekday_availabilities_path %>